#pragma once

#include "expressions/AddExpression.h"
#include "expressions/SubtractExpression.h"
#include "expressions/DivExpression.h"
#include "expressions/IdentExpression.h"
#include "expressions/MulExpression.h"
#include "expressions/NumberExpression.h"
#include "expressions/AndExpression.h"
#include "expressions/IsEqualExpression.h"
#include "expressions/IsGreaterExpression.h"
#include "expressions/IsLessExpression.h"
#include "expressions/ModuloExpression.h"
#include "expressions/OrExpression.h"

#include "statements/PrintStatement.h"
#include "statements/VarDecl.h"
#include "statements/Statement.h"
#include "statements/Assignment.h"
#include "statements/AssignmentList.h"
#include "statements/ScopeAssignmentList.h"
#include "statements/IfStatement.h"
#include "statements/WhileStatement.h"

#include "Program.h"