#pragma once

// template<typename T>
class BaseElement;
class Expression;
class NumberExpression;
class AddExpression;
class SubtractExpression;
class MulExpression;
class DivExpression;
class IdentExpression;
class Statement;
class PrintStatement;
class VarDecl;
class ClassDecl;
class MethodDecl;
class Declaration;
class DeclarationList;
class Assignment;
class AssignmentList;
class ScopeAssignmentList;
class IfStatement;
class WhileStatement;
class Program;
class AndExpression;
class IsEqualExpression;
class IsGreaterExpression;
class IsLessExpression;
class ModuloExpression;
class OrExpression;
class MainClass;